import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Download } from "lucide-react";
import { apiGet } from "@/lib/api";
import type { AnalyticsSummary, ChartPoint } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { PageHeader, SkeletonRows, Surface } from "@/components/rohly/Primitives";
import { StatusBadge } from "@/components/rohly/StatusBadge";

function Bars({ points }: { points: ChartPoint[] }) {
  const max = Math.max(1, ...points.map((point) => point.sends));
  return <div className="flex h-56 items-end gap-1.5 px-1 pt-6" data-testid="analytics-chart">{points.map((point) => <div key={point.date} className="group relative flex h-full flex-1 items-end"><div className="w-full rounded-t-sm bg-blue-600 transition-[opacity] hover:opacity-80" style={{ height: `${Math.max(2, (point.sends / max) * 100)}%` }} /><div className="pointer-events-none absolute bottom-full left-1/2 z-10 mb-2 hidden -translate-x-1/2 whitespace-nowrap rounded bg-slate-950 px-2 py-1 text-[10px] text-white group-hover:block">{point.date}: {point.sends} sends · {point.replies} replies</div></div>)}</div>;
}

export default function Analytics() {
  const [days, setDays] = useState(30);
  const query = useQuery({ queryKey: ["analytics", days], queryFn: () => apiGet<AnalyticsSummary>(`/product/analytics?days=${days}`) });
  const data = query.data;
  return <div data-testid="analytics-page"><PageHeader eyebrow="Reporting" title="Analytics" description="Understand campaign and inbox performance using real send and reply outcomes." actions={<div className="flex gap-2"><select value={days} onChange={(event) => setDays(Number(event.target.value))} className="h-9 rounded-md border border-slate-200 bg-white px-3 text-xs" data-testid="analytics-range-select"><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select><Button variant="outline" size="sm" className="gap-2" onClick={() => window.print()}><Download size={13} /> Export</Button></div>} />{query.isLoading || !data ? <SkeletonRows rows={8} /> : <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Emails sent", data.emails_sent], ["Reply rate", `${data.reply_rate}%`], ["Positive reply rate", `${data.positive_reply_rate}%`], ["Failure rate", `${data.bounce_rate}%`]].map(([label, value]) => <Surface key={label} className="p-4" testId={`analytics-${String(label).toLowerCase().replaceAll(" ", "-")}`}><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-4 text-3xl font-semibold tracking-[-0.04em]">{value}</p></Surface>)}</div><Surface className="mt-4 p-5" testId="email-volume-chart"><div><h2 className="text-sm font-semibold">Email volume</h2><p className="mt-1 text-xs text-slate-500">Daily sends with hover details</p></div><Bars points={data.chart} /></Surface><div className="mt-4 grid gap-4 xl:grid-cols-2"><Surface className="overflow-hidden" testId="campaign-comparison"><div className="border-b border-slate-200 px-4 py-3"><h2 className="text-sm font-semibold">Campaign comparison</h2></div><div className="divide-y divide-slate-100">{data.campaign_comparison.slice(0, 8).map((item) => <div key={item.id} className="flex items-center justify-between gap-4 px-4 py-3"><div className="min-w-0"><p className="truncate text-xs font-semibold">{item.name}</p><p className="mt-1 text-[10px] text-slate-400">{item.sent} sent · {item.replies} replies</p></div><p className="text-sm font-semibold">{item.reply_rate}%</p></div>)}</div></Surface><Surface className="overflow-hidden" testId="inbox-performance"><div className="border-b border-slate-200 px-4 py-3"><h2 className="text-sm font-semibold">Inbox performance</h2></div><div className="divide-y divide-slate-100">{data.inbox_performance.slice(0, 8).map((item) => <div key={item.id} className="flex items-center justify-between gap-4 px-4 py-3"><div className="min-w-0"><p className="truncate text-xs font-semibold">{item.email}</p><p className="mt-1 text-[10px] text-slate-400">{item.sent_today} sent today · {item.failed_last_7_days} failures</p></div><StatusBadge status={item.health} /></div>)}</div></Surface></div></>}</div>;
}