import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Check, Sparkles } from "lucide-react";
import { apiGet } from "@/lib/api";
import type { BillingConfiguration, BillingPlan } from "@/lib/types";
import { PageHeader, SkeletonRows, Surface } from "@/components/rohly/Primitives";

export default function Billing() {
  const [annual, setAnnual] = useState(false);
  const status = useQuery({ queryKey: ["billing-status"], queryFn: () => apiGet<BillingConfiguration>("/billing/status") });
  const plans = useQuery({ queryKey: ["billing-plans"], queryFn: () => apiGet<BillingPlan[]>("/billing/plans") });
  return <div data-testid="billing-page"><PageHeader eyebrow="Subscription" title="Billing" description="Choose the plan that matches your sending volume and growth." /><Surface className="mb-5 overflow-hidden border-blue-100 bg-gradient-to-r from-blue-50/80 via-white to-indigo-50/60 p-4" testId="billing-intro"><div className="flex items-start gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-blue-700 text-white shadow-sm"><Sparkles size={16} /></span><div><p className="text-sm font-semibold text-slate-900">Simple plans that scale with your outreach</p><p className="mt-1 max-w-2xl text-xs leading-relaxed text-slate-500">Start with the capacity you need today. Your workspace, campaigns, leads, and connected inboxes stay in one place as you grow.</p></div></div></Surface><div className="mb-4 flex justify-center"><div className="inline-flex rounded-md border border-slate-200 bg-white p-1"><button onClick={() => setAnnual(false)} className={`rounded px-3 py-1.5 text-xs font-semibold ${!annual ? "bg-slate-950 text-white" : "text-slate-500"}`}>Monthly</button><button onClick={() => setAnnual(true)} className={`rounded px-3 py-1.5 text-xs font-semibold ${annual ? "bg-slate-950 text-white" : "text-slate-500"}`}>Annual · save 20%</button></div></div>{plans.isLoading ? <SkeletonRows rows={6} /> : <div className="grid gap-3 lg:grid-cols-4">{plans.data?.map((plan) => <Surface key={plan.key} className={`p-4 ${plan.key === "growth" ? "border-blue-300 ring-1 ring-blue-100" : ""}`} testId={`billing-plan-${plan.key}`}><div className="flex items-center justify-between"><h2 className="text-base font-semibold">{plan.name}</h2>{plan.key === "growth" ? <span className="rounded bg-blue-50 px-2 py-1 text-[9px] font-bold uppercase tracking-wide text-blue-700">Most popular</span> : null}</div><p className="mt-3 text-[26px] font-semibold tracking-[-0.04em]">${annual ? plan.annual_price.toLocaleString() : plan.monthly_price}</p><p className="mt-1 text-xs text-slate-400">per {annual ? "year" : "month"}</p><div className="mt-4 space-y-2 border-t border-slate-100 pt-4 text-xs text-slate-600"><p>{plan.monthly_email_limit.toLocaleString()} emails / month</p><p>{plan.contact_limit.toLocaleString()} contacts</p><p>{plan.inbox_limit} inboxes</p>{plan.features.map((feature) => <p key={feature} className="flex gap-2"><Check size={12} className="mt-0.5 text-emerald-600" /> {feature}</p>)}</div><div className="mt-4 rounded-md bg-slate-50 px-3 py-2 text-center text-[11px] font-medium text-slate-500">{status.data?.checkout_enabled ? "Ready to upgrade" : "Online checkout coming soon"}</div></Surface>)}</div>}</div>;
}