import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, Download, FlaskConical, Pause, Pencil, Play, Square } from "lucide-react";
import { toast } from "sonner";
import { apiGet, apiPatch } from "@/lib/api";
import type { CsvCampaign, ScheduledEmail } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { SkeletonRows, Surface } from "@/components/rohly/Primitives";
import { StatusBadge } from "@/components/rohly/StatusBadge";
import { TestEmailDialog } from "@/components/rohly/TestEmailDialog";
import { formatCampaignDateTime } from "@/lib/dates";

const tabs = ["Overview", "Sequence", "Leads", "Analytics", "Activity", "Settings"];

export default function CampaignDetail() {
  const { campaignId } = useParams();
  const [tab, setTab] = useState("Overview");
  const [testOpen, setTestOpen] = useState(false);
  const client = useQueryClient();
  const campaigns = useQuery({ queryKey: ["csv-campaigns"], queryFn: () => apiGet<CsvCampaign[]>("/csv/campaigns") });
  const activity = useQuery({ queryKey: ["campaign-activity", campaignId], queryFn: () => apiGet<ScheduledEmail[]>(`/csv/campaigns/${campaignId}/activity`), enabled: Boolean(campaignId) });
  const campaign = campaigns.data?.find((item) => item.id === campaignId);
  const status = useMutation({
    mutationFn: (value: "running" | "paused" | "stopped") => apiPatch<CsvCampaign>(`/csv/campaigns/${campaignId}/status`, { status: value }),
    onSuccess: (_, value) => { client.invalidateQueries({ queryKey: ["csv-campaigns"] }); toast.success(`Campaign ${value}`); },
  });
  if (campaigns.isLoading || !campaign) return <SkeletonRows rows={8} />;
  const events = activity.data ?? [];
  const leadEmails = [...new Set(events.map((item) => item.recipient_email))];

  const nextScheduled = events.filter((item) => item.status === "scheduled").sort((a, b) => new Date(a.scheduled_at).getTime() - new Date(b.scheduled_at).getTime())[0];
  const completed = events.filter((item) => item.status === "sent").length;
  const totalPlanned = Math.max(1, campaign.total_leads * Math.max(1, campaign.steps.length));
  const progress = Math.min(100, Math.round((completed / totalPlanned) * 100));

  return <div data-testid="campaign-detail-page" className="-mx-4 -mt-4 min-h-[calc(100vh-5rem)] bg-white sm:-mx-6 lg:-mx-7">
    <div className="border-b border-slate-200 bg-white px-5 py-4 lg:px-7"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><Link to="/campaigns" className="flex size-8 items-center justify-center rounded-lg border border-slate-200 text-slate-500 hover:bg-slate-50"><ArrowLeft size={14} /></Link><div><div className="flex items-center gap-2"><h1 className="text-[16px] font-bold text-slate-900">{campaign.name}</h1><StatusBadge status={campaign.status} /></div><p className="mt-1 text-[10px] text-slate-400">Created {new Date(campaign.created_at).toLocaleString(undefined, { month: "short", day: "numeric", year: "numeric", hour: "2-digit", minute: "2-digit" })}</p></div></div><div className="flex flex-wrap gap-2"><Button onClick={() => setTestOpen(true)} variant="outline" className="h-9 gap-2 rounded-lg text-xs"><FlaskConical size={13} /> Send test</Button><Button render={<Link to={`/campaigns/${campaign.id}/edit`} />} variant="outline" className="h-9 gap-2 rounded-lg text-xs"><Pencil size={13} /> Edit</Button>{campaign.status === "running" ? <Button onClick={() => status.mutate("paused")} variant="outline" className="h-9 gap-2 rounded-lg text-xs"><Pause size={13} /> Pause</Button> : campaign.status === "paused" ? <Button onClick={() => status.mutate("running")} variant="outline" className="h-9 gap-2 rounded-lg text-xs"><Play size={13} /> Resume</Button> : null}{!["stopped", "completed"].includes(campaign.status) ? <Button onClick={() => status.mutate("stopped")} variant="outline" className="h-9 gap-2 rounded-lg text-xs text-red-600"><Square size={12} /> Stop</Button> : null}<Button variant="default" onClick={() => { window.location.href = `/api/csv/campaigns/${campaign.id}/export`; }} className="h-9 gap-2 rounded-lg bg-violet-600 text-xs hover:bg-violet-700"><Download size={13} /> Export</Button></div></div></div>
    <div className="grid grid-cols-2 divide-x border-b border-slate-100 bg-slate-50/50 sm:grid-cols-3 lg:grid-cols-6">{[{ icon: CalendarClock, label: "Follow-ups Today", value: events.filter((item) => item.step_key !== campaign.steps[0]?.key && item.status === "scheduled").length },{ icon: Webhook, label: "Webhooks", value: "Disabled" },{ icon: Send, label: "Sending Capacity", value: campaign.inbox_ids.length + " inbox" + (campaign.inbox_ids.length === 1 ? "" : "es") },{ icon: BarChart3, label: "Active Sequences", value: campaign.steps.length },{ icon: Mail, label: "Emails Sent", value: completed },{ icon: CalendarClock, label: "Next Email", value: nextScheduled ? formatCampaignDateTime(nextScheduled.scheduled_at, campaign.timezone) : "None scheduled" }].map(({ icon: Icon, label, value }) => <div key={label} className="flex min-h-[68px] items-center gap-3 px-4 py-3 lg:px-5"><span className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-violet-50 text-violet-600"><Icon size={14} /></span><div className="min-w-0"><p className="text-[10px] font-medium text-slate-400">{label}</p><p className="mt-1 truncate text-xs font-semibold text-slate-700">{value}</p></div></div>)}</div>
    <div className="flex gap-1 overflow-x-auto border-b border-slate-200 px-5 lg:px-7" role="tablist">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`relative whitespace-nowrap px-4 py-3.5 text-xs font-semibold ${tab === item ? "text-violet-600" : "text-slate-400 hover:text-slate-700"}`} role="tab" aria-selected={tab === item}>{item}{tab === item ? <span className="absolute inset-x-1 bottom-0 h-0.5 rounded-full bg-violet-600" /> : null}</button>)}</div>
    <div className="px-5 py-5 lg:px-7">{tab === "Overview" ? <Overview campaign={campaign} events={events} progress={progress} /> : null}{tab === "Sequence" ? <Sequence campaign={campaign} events={events} /> : null}{tab === "Leads" ? <Leads events={events} leadEmails={leadEmails} /> : null}{tab === "Analytics" ? <CampaignAnalytics campaign={campaign} /> : null}{tab === "Activity" ? <Activity events={events} timezone={campaign.timezone} /> : null}{tab === "Settings" ? <Surface className="p-5" testId="campaign-settings"><div className="flex items-center gap-2"><Settings2 size={16} className="text-violet-600" /><h2 className="text-sm font-semibold">Campaign settings</h2></div><p className="mt-2 text-xs leading-relaxed text-slate-500">Timezone: {campaign.timezone}. Use Edit to change source rows, mappings, inboxes, or schedule. Sent, failed, and replied history is protected while future unsent emails are rebuilt.</p></Surface> : null}</div>
    {testOpen ? <TestEmailDialog campaignId={campaign.id} inboxCount={campaign.inbox_ids.length} onClose={() => setTestOpen(false)} /> : null}
  </div>

function Overview({ campaign, events, progress }: { campaign: CsvCampaign; events: ScheduledEmail[]; progress: number }) {
  const metrics = [{ label: "Total leads contacted", value: campaign.emails_sent ? campaign.total_leads : 0, icon: Users, tone: "text-violet-600" },{ label: "Emails sent", value: campaign.emails_sent, icon: Mail, tone: "text-violet-600" },{ label: "Replies", value: campaign.replies, icon: Send, tone: "text-cyan-600" },{ label: "Positive replies", value: campaign.positive_replies, icon: BarChart3, tone: "text-emerald-600" },{ label: "Failed", value: campaign.failed_emails, icon: Square, tone: "text-red-500" }];
  return <div className="space-y-5">
    <div className="grid gap-4 xl:grid-cols-[1.05fr_1.6fr]"><Surface className="overflow-hidden bg-gradient-to-br from-violet-50 via-white to-fuchsia-50 p-5" testId="campaign-progress"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold text-slate-600">Campaign progress</p><p className="mt-1 text-[10px] text-slate-400">Email sends tracking</p></div><StatusBadge status={campaign.status} /></div><div className="mt-6 flex items-end gap-2"><span className="text-4xl font-bold tracking-tight text-slate-900">{progress}%</span><span className="pb-1 text-xs text-slate-400">complete</span></div><p className="mt-1 text-xs text-slate-500">{events.filter((item)=>item.status==="sent").length} of {Math.max(1,campaign.total_leads*Math.max(1,campaign.steps.length))} sends processed</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-violet-500" style={{ width: progress + "%" }} /></div></Surface>
      <Surface className="p-5" testId="campaign-metrics"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(({ label, value, icon: Icon, tone }) => <div key={label} className="rounded-xl bg-slate-50 p-4"><Icon size={15} className={tone} /><p className="mt-3 text-[10px] text-slate-400">{label}</p><p className={`mt-1 text-2xl font-bold ${tone}`}>{value}</p></div>)}</div></Surface></div>
    <Surface className="p-5" testId="campaign-send-forecast"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-semibold text-slate-900">Campaign Send Forecast vs. Actual</h2><p className="mt-1 text-[10px] text-slate-400">Scheduled delivery and actual send progress</p></div><div className="flex gap-2 text-[10px]"><span className="rounded-md bg-violet-50 px-3 py-2 font-semibold text-violet-600">Sent {campaign.emails_sent}</span><span className="rounded-md bg-slate-50 px-3 py-2 font-semibold text-slate-500">Scheduled {campaign.emails_scheduled}</span><span className="rounded-md bg-red-50 px-3 py-2 font-semibold text-red-500">Failed {campaign.failed_emails}</span></div></div><div className="mt-6 flex h-40 items-end gap-3 border-b border-slate-100 px-3">{[campaign.emails_sent,campaign.emails_scheduled,campaign.replies,campaign.positive_replies].map((value,index)=><div key={index} className="flex h-full flex-1 items-end"><div className={`w-full rounded-t-md ${index===0?"bg-violet-400":index===1?"bg-fuchsia-300":index===2?"bg-cyan-400":"bg-emerald-400"}`} style={{height:Math.max(4,Math.min(100,(value/Math.max(1,campaign.total_leads*Math.max(1,campaign.steps.length)))*100))+"%"}} /></div>)}</div><div className="mt-3 flex justify-center gap-5 text-[10px] text-slate-400"><span>● Sent</span><span>● Scheduled</span><span>● Replies</span><span>● Positive</span></div></Surface>
    <Surface className="overflow-hidden" testId="campaign-source"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-semibold">Campaign details</h2></div><div className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-[10px] text-slate-400">Source</p><p className="mt-1 text-xs font-semibold">{campaign.source_filename}</p></div><div><p className="text-[10px] text-slate-400">Sending inboxes</p><p className="mt-1 text-xs font-semibold">{campaign.inbox_ids.length}</p></div><div><p className="text-[10px] text-slate-400">Sending window</p><p className="mt-1 text-xs font-semibold">{campaign.sending_window_start} – {campaign.sending_window_end}</p></div><div><p className="text-[10px] text-slate-400">Timezone</p><p className="mt-1 text-xs font-semibold">{campaign.timezone}</p></div></div></Surface>
  </div>;
}

function Sequence({ campaign, events }: { campaign: CsvCampaign; events: ScheduledEmail[] }) {
  return <div className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Sequence Analytics & Management</h2><p className="mt-1 text-[10px] text-slate-400">{campaign.steps.length} steps in this campaign</p></div><Button variant="outline" className="h-8 gap-2 text-xs"><span>+</span> Add Sequence</Button></div>{campaign.steps.map((step,index)=>{const rows=events.filter((item)=>item.step_key===step.key);const sent=rows.filter((item)=>item.status==="sent").length;const replies=rows.filter((item)=>item.replied_at).length;const failed=rows.filter((item)=>item.status==="failed").length;return <Surface key={step.key} className="overflow-hidden" testId={`sequence-step-${index}`}><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><p className="text-xs font-bold text-slate-900">Email {index+1} – Email Outreach <span className="ml-1 font-medium text-orange-500">• {replies ? "Engaged" : "Medium Engagement"}</span></p><p className="mt-2 text-[11px] text-slate-500">Subject: <span className="font-medium text-slate-700">{step.label}</span></p></div><Button variant="outline" size="icon" className="size-8"><Pencil size={13}/></Button></div><div className="grid grid-cols-2 divide-x sm:grid-cols-4"><MetricMini label="Sent" value={sent} tone="violet"/><MetricMini label="Replies" value={replies} tone="cyan"/><MetricMini label="Failed" value={failed} tone="red"/><MetricMini label="Scheduled" value={rows.filter((item)=>item.status==="scheduled").length} tone="slate"/></div></Surface>})}</div>;
}

function MetricMini({ label, value, tone }: { label:string; value:number; tone:"violet"|"cyan"|"red"|"slate" }) {
  const tones={violet:"text-violet-600",cyan:"text-cyan-600",red:"text-red-500",slate:"text-slate-600"};
  return <div className="px-4 py-4 text-center"><p className={`text-lg font-semibold ${tones[tone]}`}>{value}</p><p className="mt-1 text-[10px] text-slate-400">{label}</p></div>;
}

function Leads({ events, leadEmails }: { events: ScheduledEmail[]; leadEmails: string[] }) {
  return <Surface testId="campaign-leads-list"><div className="divide-y divide-slate-100">{leadEmails.map((email) => { const rows = events.filter((item) => item.recipient_email === email); return <div key={email} className="grid gap-3 px-4 py-3 text-xs sm:grid-cols-[1fr_1fr_120px]"><div><p className="font-semibold">{rows[0]?.first_name || email}</p><p className="mt-1 text-slate-400">{email}</p></div><p className="text-slate-500">{rows[0]?.company || "—"}</p><StatusBadge status={rows.some((item) => item.replied_at) ? "replied" : rows[0]?.status || "scheduled"} /></div>; })}</div></Surface>;
}

function Activity({ events, timezone }: { events: ScheduledEmail[]; timezone: string }) {
  return <Surface testId="campaign-activity"><div className="border-b border-slate-200 bg-slate-50 px-4 py-2.5 text-[11px] font-medium text-slate-500" data-testid="campaign-timezone-label">All times shown in {timezone}</div><div className="divide-y divide-slate-100">{events.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 px-4 py-3"><div><p className="text-xs font-semibold">{item.first_name || item.recipient_email} · {item.step_label}</p><p className="mt-1 text-[11px] text-slate-400">{item.subject}</p></div><div className="text-right"><StatusBadge status={item.status} /><p className="mt-1 text-[10px] text-slate-400" data-testid={`campaign-event-time-${item.id}`}>{formatCampaignDateTime(item.scheduled_at, timezone)}</p></div></div>)}</div></Surface>;
}

function CampaignAnalytics({ campaign }: { campaign: CsvCampaign }) {
  return <Surface className="p-5" testId="campaign-analytics"><h2 className="text-sm font-semibold">Campaign conversion</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-md bg-slate-50 p-4"><p className="text-xs text-slate-500">Reply rate</p><p className="mt-2 text-2xl font-semibold">{campaign.emails_sent ? ((campaign.replies / campaign.emails_sent) * 100).toFixed(1) : "0.0"}%</p></div><div className="rounded-md bg-slate-50 p-4"><p className="text-xs text-slate-500">Positive replies</p><p className="mt-2 text-2xl font-semibold">{campaign.positive_replies}</p></div><div className="rounded-md bg-slate-50 p-4"><p className="text-xs text-slate-500">Scheduled</p><p className="mt-2 text-2xl font-semibold">{campaign.emails_scheduled}</p></div></div></Surface>;
}