import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Download, Search } from "lucide-react";
import { apiGet } from "@/lib/api";
import type { LeadPage } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { EmptyState, PageHeader, SkeletonRows, Surface } from "@/components/rohly/Primitives";
import { StatusBadge } from "@/components/rohly/StatusBadge";

export default function Leads() {
  const [q, setQ] = useState("");
  const [page, setPage] = useState(1);
  const query = useQuery({ queryKey: ["leads", q, page], queryFn: () => apiGet<LeadPage>(`/product/leads?page=${page}&page_size=25&q=${encodeURIComponent(q)}`) });
  return <div data-testid="leads-page"><PageHeader eyebrow="Audience" title="Leads" description="Review every scheduled contact, campaign, status, and next step." /><Surface testId="leads-table"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-4"><div className="relative w-full max-w-sm"><Search size={14} className="absolute left-3 top-2.5 text-slate-400" /><Input value={q} onChange={(event) => { setQ(event.target.value); setPage(1); }} placeholder="Search name, email, company, campaign" className="h-9 pl-9" data-testid="lead-search-input" /></div><Button variant="outline" size="sm" className="gap-2" onClick={() => window.print()} data-testid="export-leads-button"><Download size={13} /> Export view</Button></div>{query.isLoading ? <SkeletonRows rows={8} /> : query.data?.items.length ? <><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left"><thead className="bg-slate-50 text-[10px] font-bold uppercase tracking-[0.08em] text-slate-500"><tr><th className="px-4 py-3">Name</th><th className="px-4 py-3">Email</th><th className="px-4 py-3">Company</th><th className="px-4 py-3">Campaign</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Last activity</th><th className="px-4 py-3">Next step</th><th className="px-4 py-3">Inbox</th></tr></thead><tbody className="divide-y divide-slate-100">{query.data.items.map((lead) => <tr key={lead.id} className="text-xs hover:bg-slate-50/70"><td className="px-4 py-3.5 font-semibold text-slate-900">{lead.name}</td><td className="px-4 py-3.5 text-slate-600">{lead.email}</td><td className="px-4 py-3.5 text-slate-600">{lead.company || "—"}</td><td className="px-4 py-3.5 text-slate-600">{lead.campaign_name}</td><td className="px-4 py-3.5"><StatusBadge status={lead.status} /></td><td className="px-4 py-3.5 text-slate-500">{lead.last_activity ? new Date(lead.last_activity).toLocaleString() : "—"}</td><td className="px-4 py-3.5"><p className="font-medium text-slate-700">{lead.next_step || "Complete"}</p><p className="mt-1 text-[10px] text-slate-400">{lead.next_step_at ? new Date(lead.next_step_at).toLocaleString() : ""}</p></td><td className="px-4 py-3.5 text-slate-500">{lead.inbox_email}</td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-slate-200 px-4 py-3"><p className="text-xs text-slate-500">{query.data.total} leads</p><div className="flex gap-2"><Button size="sm" variant="outline" disabled={page === 1} onClick={() => setPage((value) => value - 1)}>Previous</Button><Button size="sm" variant="outline" disabled={page * 25 >= query.data.total} onClick={() => setPage((value) => value + 1)}>Next</Button></div></div></> : <EmptyState title="No scheduled leads" description="Leads appear here after a CSV campaign is launched." />}</Surface></div>;
}