import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bell, Building2, CreditCard, KeyRound, Send, User } from "lucide-react";
import { toast } from "sonner";
import { apiGet, apiPatch } from "@/lib/api";
import type { UserPublic } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageHeader, Surface } from "@/components/rohly/Primitives";

const sections = [{ id: "profile", label: "Profile", icon: User }, { id: "security", label: "Security", icon: KeyRound }, { id: "workspace", label: "Workspace", icon: Building2 }, { id: "sending", label: "Sending", icon: Send }, { id: "notifications", label: "Notifications", icon: Bell }];

export default function SettingsPage() {
  const [section, setSection] = useState("profile");
  const me = useQuery({ queryKey: ["me"], queryFn: () => apiGet<UserPublic>("/auth/me") });
  const [name, setName] = useState(""); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState("");
  const client = useQueryClient();
  const profile = useMutation({ mutationFn: () => apiPatch<UserPublic>("/auth/profile", { name: name || me.data?.name }), onSuccess: (user) => { client.setQueryData(["me"], user); toast.success("Profile updated"); } });
  const password = useMutation({ mutationFn: () => apiPatch<void>("/auth/password", { current_password: currentPassword, new_password: newPassword }), onSuccess: () => { toast.success("Password changed. Sign in again on your next visit."); setCurrentPassword(""); setNewPassword(""); }, onError: () => toast.error("Current password is incorrect") });
  return <div data-testid="settings-page"><PageHeader eyebrow="Workspace controls" title="Settings" description="Manage your account, security, workspace, and sending defaults." /><div className="grid gap-4 lg:grid-cols-[220px_1fr]"><Surface className="h-fit p-2" testId="settings-navigation">{sections.map((item) => <button key={item.id} onClick={() => setSection(item.id)} className={`flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-left text-sm font-medium ${section === item.id ? "bg-blue-50 text-blue-800" : "text-slate-600 hover:bg-slate-50"}`}><item.icon size={15} /> {item.label}</button>)}<div className="mt-2 border-t border-slate-100 pt-2"><div className="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm text-slate-400"><CreditCard size={15} /> Billing <span className="ml-auto text-[9px] font-bold uppercase">Hidden</span></div></div></Surface><Surface className="p-5" testId="settings-content">{section === "profile" ? <div><h2 className="text-base font-semibold">Profile</h2><p className="mt-1 text-xs text-slate-500">Update the name shown across Rohly.</p><label className="mt-6 block max-w-md text-xs font-semibold">Name<Input value={name} onChange={(event) => setName(event.target.value)} placeholder={me.data?.name} className="mt-2 h-10" /></label><label className="mt-4 block max-w-md text-xs font-semibold">Email<Input value={me.data?.email ?? ""} disabled className="mt-2 h-10 bg-slate-50" /></label><Button onClick={() => profile.mutate()} className="mt-5 bg-blue-700 hover:bg-blue-800">Save profile</Button></div> : section === "security" ? <div><h2 className="text-base font-semibold">Security</h2><p className="mt-1 text-xs text-slate-500">Change your password. Active sessions are revoked after the change.</p><label className="mt-6 block max-w-md text-xs font-semibold">Current password<Input type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} className="mt-2 h-10" /></label><label className="mt-4 block max-w-md text-xs font-semibold">New password<Input type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} className="mt-2 h-10" /></label><Button onClick={() => password.mutate()} disabled={newPassword.length < 10} className="mt-5 bg-blue-700 hover:bg-blue-800">Update password</Button></div> : <div><h2 className="text-base font-semibold capitalize">{section}</h2><p className="mt-1 text-xs text-slate-500">These settings are derived from live workspace and inbox configuration.</p><div className="mt-6 rounded-md border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600">{section === "workspace" ? "Rohly · Deepanshu's workspace · Owner access" : section === "sending" ? "Campaign timezone and per-inbox limits are configured during campaign and inbox setup." : "Operational notifications appear in the Rohly top bar."}</div></div>}</Surface></div></div>;
}